#pragma once
#include <string>
#include <utility>
#include <vector>

namespace hft {

inline const std::vector<std::pair<std::string, std::string>>
    kSymbolCompanyList = {{"NEX.FR", "Nexans France"},
                          {"TTE.FR", "Total Energies"},
                          {"BY6.DE", "BYD"},
                          {"SAF.FR", "Safran"},
                          {"ASML", "ASML"},
                          {"ASML.AS", "ASML"},
                          {"ASML.NL", "ASML"},
                          {"ENI.IT", "Eni"},
                          {"NOKIA.FI", "Nokia"},
                          {"KOG.NO", "Kongsberg"},
                          {"5711.T", "Mitsubishi Materials"},
                          {"TYO:5711", "Mitsubishi Materials"},
                          {"4043.T", "Tokuyama"},
                          {"TYO:4043", "Tokuyama"},
                          {"LEA.US", "Lear"},
                          {"AWK.US", "American Water Works"},
                          {"CEG.US", "Constellation Energy Corp"},
                          {"VST.US", "Vistra Energy"},
                          {"NIO.US", "Nio"},
                          {"XPEV.US", "Xpeng"},
                          {"INTC", "Intel"},
                          {"INTC.US", "Intel"},
                          {"OKLO.US", "Oklo Inc"},
                          {"SNDK.US", "SanDisk"},
                          {"MU.US", "Micron"},
                          {"STX.US", "Seagate"},
                          {"WDC.US", "Western Digital"},
                          {"PSTG.US", "Pure Storage"},
                          {"LMT.US", "Lockheed Martin"},
                          {"HWM.US", "Howmet Aerospace"},
                          {"RTX.US", "Raytheon Tech"},
                          {"NOC.US", "Northrop Grumman"},
                          {"GSM", "Ferroglobe"},
                          {"WCH", "Wacker Chemie"},
                          {"WCH.DE", "Wacker Chemie"},
                          {"010060.KS", "OCI Holdings"},
                          {"REC.OL", "REC Silicon"},
                          {"4063.T", "Shin-Etsu Chemical"},
                          {"3436.T", "SUMCO"},
                          {"6488.TWO", "GlobalWafers"},
                          {"WAF", "Siltronic"},
                          {"WAF.DE", "Siltronic"},
                          {"4186.T", "Tokyo Ohka Kogyo"},
                          {"DD", "DuPont"},
                          {"4901.T", "Fujifilm Holdings"},
                          {"4005.T", "Sumitomo Chemical"},
                          {"ENTG", "Entegris"},
                          {"AI", "Air Liquide"},
                          {"AIRP.PA", "Air Liquide"},
                          {"LIN", "Linde"},
                          {"APD", "Air Products"},
                          {"MRK", "Merck KGaA"},
                          {"MRK.DE", "Merck KGaA"},
                          {"MKSI", "MKS Instruments"},
                          {"AMAT", "Applied Materials"},
                          {"LRCX", "Lam Research"},
                          {"8035.T", "Tokyo Electron"},
                          {"KLAC", "KLA"},
                          {"ASM", "ASM International"},
                          {"ASM.AS", "ASM International"},
                          {"6857.T", "Advantest"},
                          {"7735.T", "SCREEN Holdings"},
                          {"SNPS", "Synopsys"},
                          {"CDNS", "Cadence Design Systems"},
                          {"SIE", "Siemens AG"},
                          {"SIE.DE", "Siemens AG"},
                          {"KEYS", "Keysight Technologies"},
                          {"ARM", "Arm Holdings"},
                          {"6533.TWO", "Andes Technology"},
                          {"AMD", "AMD"},
                          {"AAPL", "Apple"},
                          {"QCOM", "Qualcomm"},
                          {"2454.TW", "MediaTek"},
                          {"NVDA", "NVIDIA"},
                          {"005930.KS", "Samsung Electronics"},
                          {"IBM", "IBM"},
                          {"2330.TW", "TSMC"},
                          {"TSM", "TSMC"},
                          {"GFS", "GlobalFoundries"},
                          {"2303.TW", "UMC"},
                          {"UMC", "UMC"},
                          {"0981.HK", "SMIC"},
                          {"TSEM", "Tower Semiconductor"},
                          {"5347.TWO", "VIS"},
                          {"4062.T", "Ibiden"},
                          {"3037.TW", "Unimicron"},
                          {"ATS", "AT&S"},
                          {"ATS.VI", "AT&S"},
                          {"3189.TW", "Kinsus Interconnect"},
                          {"009150.KS", "Samsung Electro-Mechanics"},
                          {"2802.T", "Ajinomoto"},
                          {"3711.TW", "ASE Technology Holding"},
                          {"ASX", "ASE Technology Holding"},
                          {"AMKR", "Amkor Technology"},
                          {"600584.SS", "JCET"},
                          {"6239.TW", "Powertech Technology"},
                          {"8150.TW", "ChipMOS"},
                          {"IMOS", "ChipMOS"},
                          {"2449.TW", "KYEC"},
                          {"DELL", "Dell Technologies"},
                          {"HPQ", "HP Inc."},
                          {"0992.HK", "Lenovo Group"},
                          {"2357.TW", "ASUS"},
                          {"2353.TW", "Acer"},
                          {"SMCI", "Supermicro"},
                          {"CSCO", "Cisco"},
                          {"HPE", "HPE"}};

}  // namespace hft
