#!/usr/bin/env python3
import argparse
from pathlib import Path

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--info", required=True)
    args = ap.parse_args()

    text = Path(args.info).read_text(encoding="utf-8", errors="ignore").splitlines()
    has_brf = any(line.startswith("BRF:") for line in text)
    has_brh = any(line.startswith("BRH:") for line in text)

    if not (has_brf and has_brh):
        raise SystemExit("Branch coverage data was not generated by lcov (missing BRF/BRH entries).")

    print("Branch coverage data detected.")

if __name__ == "__main__":
    main()
